### ISSUE TITLE
[Bug]: Compatibility issue with Tough as Nails

### ISSUE THREAD

**Issue by festro** [Cheos137/ArmorpointsPlusplus#28] opened 2022-05-27 23:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The latest version (3.0.2) removes the water and temperature element of the GUI from Tough as Nails, leading to much sadness involving dehydration and hypothermia.

### Version

Other (this list is not up to date - again...)

### Version

forge-1.12.2-3.0.2

### To Reproduce

install tough as Nails (3.1.0.141-universal)
Install Armor points ++ (3.0.2)

### Expexted Behavior

Tough as nails GUI should be present

### Additional Context

Tough Expansion as well as serene seasons are also installed , but reverting this mod to previous release fixes problem.

**Comment by Cheos137** [comment] 2022-05-28 07:26
Do you mind sharing which release fixes the problem?
v3.0.1 or 2.x.x?

**Comment by festro** [comment] 2022-05-28 22:58
3.0.1

**Comment by Cheos137** [comment] 2022-05-29 14:45
I've looked into it for quite a few hours now... still had no luck finding the root issue - by now i've only found things that made the issues worse...

This bug is quite a frustrating one, it'll probably take some time to fix

meanwhile, as 3.0.1 does not include any critical fixes for 1.12.2 (it only includes a fix for a bug that affected - as far as i know - solely journeymap in 1.16.x - there might be more mods affected by the issue fixed in 3.0.2 but most things will work fine with 3.0.1, too), it's a solid alternative

**Comment by Cheos137** [comment] 2022-05-29 16:13
It was quite frustrating to search for this bug, but i think i've found it... it was caused by some weird quirk in the 1.12 forge eventbus

**Closed** 2022-05-29 16:14 UTC
Labels: type: bug, resolution: future update, minecraft: 1.12, priority: medium

**Comment by Cheos137** [comment] 2022-05-29 16:20
The CurseForge page currently doesn't load in for me - i'll upload the patch as soon as i can

**Comment by festro** [comment] 2022-05-30 01:51
Thanks, loving the mod as I like to see my stats, so not being able to see how thirsty or temperature was literally killing me. Glad to hear the problem is potentially fixed, testing it right now so we'll see if it fixed.

**Comment by festro** [comment] 2022-05-30 02:12
Yep this update fixed it, Thanks!
