### ISSUE TITLE
[Bug]: The render is not correct.

### ISSUE THREAD

**Issue by linxcy** [Cheos137/ArmorpointsPlusplus#21] opened 2022-03-25 06:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The render of achievement gui is not correct.
Also the gui of Draconic Evolution.

### Version

BETA 3.0.0 for Minecraft Forge 1.12.2

### Version

forge 14.23.5.2860

### Screenshots

![image](https://user-images.githubusercontent.com/67699852/160063049-6ff58cdf-662e-437e-a4bb-4881f28270b1.png)
![image](https://user-images.githubusercontent.com/67699852/160063347-2b57585a-1741-4bfc-856b-d471c441d194.png)

**Comment by Cheos137** [comment] 2022-03-25 06:48
Which mods other than Armorpoints++ and DraconicEvolution did you use?

**Comment by linxcy** [comment] 2022-03-25 08:34
![image](https://user-images.githubusercontent.com/67699852/160084420-88e17757-b3ca-4de6-a5d6-56b7bf7d72c3.png)

**Comment by linxcy** [comment] 2022-03-25 08:55
And also optfine.

**Comment by Cheos137** [comment] 2022-04-02 13:54
Not caused by any mod other than appp (happens with only appp installed) - only tested the advancement screen, though the draconic evolution gui stuff is probably related

**Comment by Cheos137** [comment] 2022-04-02 14:18
fixed in d463afc

**Closed by Cheos137** 2022-04-02 14:18 UTC
Labels: type: bug, minecraft: 1.12.2, priority: medium
