### ISSUE TITLE
[Bug]: The chat and pause menu is moved to the side in 1.16.5

### ISSUE THREAD

**Issue by ItsVenty** [Cheos137/ArmorpointsPlusplus#53] opened 2022-12-21 09:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I was testing mods to use for the game when I came across a bug. Whenever I load this mod in a world the screen is cut to the side a little along with the pause menu. Will there be a fix for this anytime soon?

### Version

3.0.x for Minecraft Forge 1.16.5

### To Reproduce

1. Download Minecraft 1.16.5 along with this mod and the JourneyMap mod
2. Run the game with the mod
3. Make a world and enter it
4. Open the pause menu (optional)

**Comment by Cheos137** [comment] 2022-12-21 10:25
Doesn't happen in latest (3.0.6) and will never happen with solely ap++ installed.

Any other mods you're using that might influence this outcome?
Otherwise i will close this as not-a-bug.

**Comment by ItsVenty** [comment] 2022-12-21 10:58
Oof mb sorry, the bug happens whenever I pair the mod with the JourneyMap mod

**Comment by Cheos137** [comment] 2022-12-21 11:44
then the only thing i can think of is this being a duplicate of #27.
If you are using 3.0.6, do you mind testing the latest 3.1.0 alpha build (available on my discord)?

**Comment by ItsVenty** [comment] 2022-12-22 08:07
Sure I'd be down

**Comment by Cheos137** [comment] 2022-12-22 08:37
can you send me the crash report? :sweat_smile:

**Comment by ItsVenty** [comment] 2022-12-22 08:40
[crash-2022-12-22_16.30.41-client.txt](https://github.com/Cheos137/ArmorpointsPlusplus/files/10285173/crash-2022-12-22_16.30.41-client.txt)

**Comment by Cheos137** [comment] 2022-12-22 08:45
Okay, the crash is unrelated to the initial issue - i don't know whether i'll have time to fix it today though

**Comment by ItsVenty** [comment] 2022-12-22 09:28
It's alright take your time :D I'll be here if you need anymore info

**Comment by Cheos137** [comment] 2022-12-22 11:46
Posted a new build (3.1.0-alpha4-exp1) on the discord aiming to fix both issues you're encountering.
(Yes, i did manage to squeeze like 20mins in to do this)

**Comment by ItsVenty** [comment] 2022-12-22 14:50
It works now, but the screen is still sideways
![2022-12-22_22 48 14](https://user-images.githubusercontent.com/83796610/209160089-0312d126-289a-42b4-b98b-ed7cd614d6cc.png)

**Comment by Cheos137** [comment] 2022-12-22 14:53
what do you mean by 'your screen being sideways'?

**Comment by ItsVenty** [comment] 2022-12-23 04:17
Apologies for the inconvenience and delay as it was nighttime for me at that point. What I meant by "sideways" is that the screen is "a few ways to a side", which I was referring to the issue of the chat and the pause menu being a bit to the side (better screenshots below).

(you can kinda see it on the top left of my image from earlier, but I can understand if that bought up insufficient information)
(oh and F3 works perfectly fine btw)
![2022-12-23_12 00 37](https://user-images.githubusercontent.com/83796610/209268484-2159a7fa-8848-427b-a294-59ff8ca4ac0d.png)
![2022-12-23_12 00 31](https://user-images.githubusercontent.com/83796610/209268501-b10299f9-02bd-4ae5-80f9-ef876ab1b160.png)

**Comment by Cheos137** [comment] 2022-12-27 09:47
I read some of JourneyMap's source code and i think I've found the problem now - published another experimental build on discord (3.1.0-alpha5-exp2)

**Comment by ItsVenty** [comment] 2022-12-29 06:20
Yeah, hate to break it to you but, it crashed again 🤣 
[crash-2022-12-29_14.01.16-client.txt](https://github.com/Cheos137/ArmorpointsPlusplus/files/10317899/crash-2022-12-29_14.01.16-client.txt)

**Comment by Cheos137** [comment] 2022-12-29 10:36
Well, crashes are _usually_ easier to fix than weird behavior... with the exception of most crashes caused by matrix stack shenanigans when working with other mods... but i think it's nothing i can't fix :)

**Comment by Cheos137** [comment] 2022-12-29 11:17
posted exp3 on discord

**Comment by ItsVenty** [comment] 2022-12-30 03:54
Alright, I've tested it and it works! I didn't get what you mean by your first comment (like... what place exactly?)
But even so, I'm glad that you could fix it in such a short notice. But I have one tiny issue to report-

Are the armor and hp values, supposed to overlap like this? 
(i mean im okay with it, but whenever I take damage, it blocks the the view of the armor value)
![2022-12-30_11 39 24](https://user-images.githubusercontent.com/83796610/210032636-78a504d7-3519-40f6-8524-fb6f80fa1448.png)

**Comment by Cheos137** [comment] 2022-12-30 10:19
> I didn't get what you mean by your first comment (like... what place exactly?)

just me ranting, nothing to worry about :)


> Are the armor and hp values, supposed to overlap like this?
> (i mean im okay with it, but whenever I take damage, it blocks the the view of the armor value)

no, they are not supposed to overlap... and looking at the code i don't know why they overlap for you
but you can manually configure their position using the config (set `textconfig.enableHealthValueConfig = true` and reposition the text using `textconfig.healthValueX` and `textconfig.healthValueY`) (correct values for x and y will probably be at around x=120 and y=39 for you)


also, i will close this issue as the actual issue (journeymap incompatibility) has been fixed

**Closed by Cheos137** 2022-12-30 10:19 UTC
Labels: bug, minecraft: 1.16, forge, compatibility
