### ISSUE TITLE
[Bug]: Health Text Value not Where it Should be.

### ISSUE THREAD

**Issue by AefRal** [Cheos137/ArmorpointsPlusplus#106] opened 2024-10-28 03:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Description

Health text value isn't where it should be.

### Version

3.1.x for Minecraft Fabric 1.20+

### To Reproduce

Install into modpack: The Realm of Immortuae.

### Expexted Behavior

For the text value of health to be to the left of the hearts.

### Additional Context

Installed mod, was happy I could see additional armor overlaid. 
Saw a number at the top of my screen, 20/20, thought it was weird.
Noticed amour value number next to bar, but health wasn't there.
Being at one heart, realized the number at the top was Health when it read 2/20.

Went into config to try to realign it.
First toggled Enable Health Value Config to false, the text at the top disappeared, which confirmed for me that it was this mod.
Toggled it back on.
Next, tried the different alignments, nothing changed.
Tried various numbers for both X and Y Health values, the text didn't budge.

### Screenshots

![Pointing it out](https://github.com/user-attachments/assets/008b3ee0-2b99-4ec7-8124-a2ed6752bdcd)

**Comment by Cheos137** [comment] 2024-10-28 16:44
manual position overrides require `enableHealthValueConfig` or `enableArmorValueConfig` to be enabled respectively.
the root cause of the text not having a valid y position to render at is due to some incompatibility (as i don't have a modlist i cannot give you any guess as to which mod might cause this incompatibility) - some mod is trying to override the health bar (as ap++ is, too), causing the text component to.. well, not get proper position information

if you find out which mod causes this, please don't hesitate to open a compatibility request ^^

will close this as invalid now as this isn't a bug

**Closed by Cheos137** 2024-10-28 16:44 UTC
Labels: bug, not a bug
