### ISSUE TITLE
[Compatibility Request]: Dhydration mod compativiity (Fabric)

### ISSUE THREAD

**Issue by evilcassus** [Cheos137/ArmorpointsPlusplus#69] opened 2023-04-02 23:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Mod name/version/id

Dehydration 1.3.3

### Link

https://www.curseforge.com/minecraft/mc-mods/dehydration

### Alternatives

Armor Points ++ still best solution for modded Minecraft. Also for "RPG-like" modpacks. But game become annoying without Dehydratation HUD.

It's duplicate of old request. But I want notice about this compability issue before AP++ v3.1.0 release

**Comment by Cheos137** [comment] 2023-04-03 00:04
#32 is literally on the v3.1.0 milestone

closing because duplicate of #32

**Closed** 2023-04-03 00:04 UTC
Labels: fabric, compatibility
