### ISSUE TITLE
[Bug]: Icons have higher y than usual

### ISSUE THREAD

**Issue by Jack-Chronicle** [Cheos137/ArmorpointsPlusplus#103] opened 2024-06-07 20:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Mod name/version/id

Appleskin / 2.5.1+1.20.3 / appleskin

### Link

https://modrinth.com/mod/appleskin

### Additional Context

The Appleskin Saturation indicator doesn't raise with the increased height the icons over the hotbar have

![2024-06-07_14-38](https://github.com/Cheos137/ArmorpointsPlusplus/assets/18507378/ce2e1b7e-4f34-488d-9f69-4a401b7928a6)

Without the mod the icons are all aligned

![2024-06-07_14-42](https://github.com/Cheos137/ArmorpointsPlusplus/assets/18507378/804b3ed4-5722-4beb-bace-40f304822894)

**Comment by Cheos137** [comment] 2024-06-09 09:26
the icons shouldn't rise any higher than usual - i'll look into it

**Comment by Jack-Chronicle** [comment] 2024-06-24 23:41
I seemed to have fixed this, it was an error with the Raised mod, disabling it's "Share" option seems to have fixed this

**Comment by Cheos137** [comment] 2024-06-25 14:34
i'll close this as invalid as this isn't caused by armorpoints++ and just some weird interaction between appleskin (which has known issues with raised on some versions) and raised

**Closed by Cheos137** 2024-06-25 14:34 UTC
Labels: bug, invalid, fabric
