### ISSUE TITLE
[Health bar issue]

### ISSUE THREAD

**Issue by Taknax** [Cheos137/ArmorpointsPlusplus#10] opened 2021-06-28 00:15 UTC
**Description**
Transparency of the heart bar is disabled and cant close the number beside.

**To Reproduce**
1. Go to 'mod option'
2. Click on 'ArmorPoints++'
3. Scroll down to 'show health value and show armor value. Both False.'
4. See error at the health bar

**Expected behavior**
The backgroung of the hearts from the health bar should be transparent and i cant close the number beside .

**Screenshots**
![2021-06-28_01 53 59](https://user-images.githubusercontent.com/66703017/123563678-567d3d00-d7b6-11eb-8d4b-fa6be82ca098.png)

**Version**
v2.0.0 [1.12.2]

**Additional context**
I use two mod which midify health value. LevelHearts and UnhealthyDying.

**Comment by Cheos137** [comment] 2021-06-28 15:31
Does not happen with Appp alone -> some kind of compat issue.
Gonna look into that.

**Comment by Cheos137** [comment] 2021-06-28 15:41
Can't reproduce with LevelHearts (1.12.2-2.0.0) and UnhealthyDying (1.3.1).
When looking at the HUD in your screenshot... that is 'Tough As Nails', right?
So, what mods are you using (full list with versions, please)

**Comment by Taknax** [comment] 2021-06-29 11:17
I figured out it just occure if "minimal HUD" is enabled in the LevelHearts mod.  Tried it without other mods. Just LH and Appp. There is a another small issue. Im gonna make some screenshots later and send you. Ty for attention.

**Comment by Cheos137** [comment] 2021-07-07 12:31
By looking at the code of LevelHearts, I saw that minimal HUD is mutually incompatible with Appp, as it overrides vanilla hud elements.
But I think I can do something about Appp glitching out because of that.

**Comment by Cheos137** [comment] 2021-07-07 13:03
should be fixed now - I added glEnableAlpha() to each of the render methods which seems to do the trick

**Closed by Cheos137** 2021-07-07 13:03 UTC
Labels: minecraft: 1.12.2, type: bug
