### ISSUE TITLE
Will cause the Dehydration thirst bar to disappear

### ISSUE THREAD

**Issue by wsxiya** [Cheos137/ArmorpointsPlusplus#65] opened 2023-03-02 05:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version currently available?

- [X] I am using the latest version currently available

### Description

Will cause the Dehydration thirst bar to disappear

### Version

3.0.x for Minecraft Fabric 1.19

### Version

fabric1.19.2

**Comment by Cheos137** [comment] 2023-03-02 05:52
duplicate of #32

**Closed** 2023-03-02 05:52 UTC
Labels: bug, duplicate
